### ISSUE TITLE
Morning Peer to Peer Code Review

### ISSUE THREAD

**Issue by altontonn** [altontonn/Global-Summit#1]

**Comment by David-Kasilia** [comment]
### **To Highlight**
Nice job :tada: .Good Implementation of the project requirements :dart: . This includes a nice website design and good use of padding and margins. However, here are a few changes you need to work on:

- For the speaker's section of the desktop, the speaker's details and image need a little bit of padding because the content is blending with the image, and its hard to see.
- Good Implementation of the background objects such as the checkered boxes, However you may consider trying to avoid overlapping of content. Kindly put that under consideration.
